# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db15b166ad35a684e8faa2fbd232dece3d190c4ce5ac8e21e86cc9b11972304db3ae2697ad26690cc2c6115fe7bb58467c83481774e68bffdd9333ff9e5eaca4

test:
  secret_key_base: 18ffc0cc770e3789f07af3a917a11b613f90e4353d4ab656ecedfd24e1b5f45bc67a8d614381e11d2546aa342481723fae4cf961396cb11af51bb5e25f82200d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
